/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author mmg_2
 */
public class VentanaCafetera extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCafetera.class.getName());

    /**
     * Creates new form VentanaCafetera
     */
    private Dispensador.facade.MaquinaCafeFacade miMaquina;

    public VentanaCafetera() {
        initComponents();

        miMaquina = new Dispensador.facade.MaquinaCafeFacade();
        redirigirConsola();

        this.setLocationRelativeTo(null); // Centrar ventana
        jTextArea2.setEditable(false);    // Que el usuario no pueda borrar el resultado
        txtLog.setEditable(false);        // Que el usuario no pueda borrar los logs   
        pintarImagen(jLabel2, "/imagenes/star.png");
    }

    private void redirigirConsola() {
        try {
            // Forzamos la salida en UTF-8
            java.io.PrintStream printStream = new java.io.PrintStream(new java.io.OutputStream() {
                @Override
                public void write(int b) throws java.io.IOException {
                    txtLog.append(String.valueOf((char) b));
                    txtLog.setCaretPosition(txtLog.getDocument().getLength());
                }
                // IMPORTANTE: Añadimos soporte para escribir arrays de bytes (strings completos)
                @Override
                public void write(byte[] b, int off, int len) throws java.io.IOException {
                    String s = new String(b, off, len, java.nio.charset.StandardCharsets.UTF_8);
                    txtLog.append(s);
                    txtLog.setCaretPosition(txtLog.getDocument().getLength());
                }
            }, true, "UTF-8");

            System.setOut(printStream);
            System.setErr(printStream);
            
        } catch (java.io.UnsupportedEncodingException ex) {
            System.err.println("Error: No se soporta UTF-8");
        }
    }
    
    private void pintarImagen(javax.swing.JLabel lbl, String ruta) {
        // 1. Cargar la imagen desde los recursos
        java.net.URL urlImagen = getClass().getResource(ruta);
        
        if (urlImagen != null) {
            // 2. Convertirla a ImageIcon
            javax.swing.ImageIcon imagenIcono = new javax.swing.ImageIcon(urlImagen);
            
            // 3. Escalarla al tamaño del JLabel (ancho y alto)
            java.awt.Image imagenEscalada = imagenIcono.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                java.awt.Image.SCALE_SMOOTH
            );
            
            // 4. Ponerla en el label
            lbl.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            lbl.setText(""); // Borrar el texto "Estrella.png"
        } else {
            System.out.println("Error: No se encontró la imagen en " + ruta);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnPedir = new javax.swing.JButton();
        sliderAzucar = new javax.swing.JSlider();
        CheckBoxMoneda = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtnCappuccino = new javax.swing.JRadioButton();
        rbtnAmericano = new javax.swing.JRadioButton();
        btnRetirarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Dispensadora de café Star");

        jLabel2.setText("Estrella.png");

        txtLog.setBackground(new java.awt.Color(204, 204, 204));
        txtLog.setColumns(20);
        txtLog.setForeground(new java.awt.Color(51, 51, 51));
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        btnEncender.setText("Encender");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnPedir.setText("Pedir café");
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });

        sliderAzucar.setMajorTickSpacing(1);
        sliderAzucar.setMaximum(3);
        sliderAzucar.setPaintLabels(true);
        sliderAzucar.setPaintTicks(true);
        sliderAzucar.setSnapToTicks(true);

        CheckBoxMoneda.setText("Moneda");
        CheckBoxMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMonedaActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(255, 204, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setText("Entregado:");

        jLabel4.setText("Ingrese moneda:");

        jLabel5.setText("Nivel de Azucar:");

        jLabel6.setText("Seleccione su orden:");

        buttonGroup1.add(rbtnCappuccino);
        rbtnCappuccino.setText("Cappuccino");

        buttonGroup1.add(rbtnAmericano);
        rbtnAmericano.setText("Americano");

        btnRetirarPedido.setText("Retirar Pedido");
        btnRetirarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRetirarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sliderAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEncender))
                                    .addGap(29, 29, 29)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CheckBoxMoneda)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbtnAmericano)
                                                .addComponent(rbtnCappuccino)))))
                                .addGap(25, 25, 25))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRetirarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnEncender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxMoneda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnCappuccino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAmericano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        txtLog.setText(""); // Limpiar pantalla al encender
        jTextArea2.setText("");
        miMaquina.botonEncender();
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // 1. Limpiar el log gris primero
        txtLog.setText(""); 
        
        // 2. Limpiar la barra naranja de entregas
        jTextArea2.setText("");

        // 3. Ejecutar la lógica de apagado
        // (Al ejecutar esto, el sistema imprimirá "Apagando máquina..." en el log vacío)
        miMaquina.botonApagar();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        // 1. Validar selección
        String tipo = "";
        if (rbtnCappuccino.isSelected()) {
            tipo = "Cappuccino";
        } else if (rbtnAmericano.isSelected()) {
            tipo = "Americano";
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Por favor selecciona un tipo de café!");
            return;
        }

        // 2. Validar moneda
        if (!CheckBoxMoneda.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Debes insertar una moneda primero!");
            return;
        }

        // 3. Obtener datos
        int azucar = sliderAzucar.getValue();
        boolean conLeche = tipo.equals("Cappuccino");

        // 4. Llamar a la Facade
        Dispensador.modelo.Cafe cafeEntregado = miMaquina.pedirCafe(tipo, conLeche, azucar);

        // 5. Mostrar resultado y limpiar
        if (cafeEntregado != null) {
            jTextArea2.setText("¡Listo! " + cafeEntregado.toString());

            // Resetear la interfaz para el siguiente cliente
            CheckBoxMoneda.setSelected(false); // Quita el check de moneda
            buttonGroup1.clearSelection();     // <--- ESTA LÍNEA DESMARCA LOS CAFÉS

        } else {
            jTextArea2.setText("Error: La máquina no pudo servir.");
        }
    }//GEN-LAST:event_btnPedirActionPerformed

    private void CheckBoxMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxMonedaActionPerformed
        if (CheckBoxMoneda.isSelected()) {
            System.out.println("Moneda detectada en ranura.");
        } else {
            System.out.println("Moneda retirada.");
        }
    }//GEN-LAST:event_CheckBoxMonedaActionPerformed

    private void btnRetirarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarPedidoActionPerformed
        // 1. Borrar el texto de la barra naranja
        jTextArea2.setText("");

        // 2. (Opcional) Imprimir en el log que se retiró
        System.out.println(">> El cliente ha retirado su pedido.");
        System.out.println("");
    }//GEN-LAST:event_btnRetirarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxMoneda;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnRetirarPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton rbtnAmericano;
    private javax.swing.JRadioButton rbtnCappuccino;
    private javax.swing.JSlider sliderAzucar;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
